# Generated by Django 2.0.7 on 2018-11-06 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0002_auto_20181106_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dot_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fax', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='none@none.com', max_length=200)),
                ('DOT_Num', models.ForeignKey(default='99999999999', on_delete=django.db.models.deletion.CASCADE, to='saferdb.Question')),
            ],
        ),
    ]
