# Generated by Django 2.0.7 on 2018-11-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0003_dot_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='DOT_Num',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
