# Generated by Django 2.0.7 on 2018-11-21 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0005_caliins'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaliIns_FK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legalN', models.CharField(max_length=200)),
                ('dbaName', models.CharField(max_length=200)),
                ('bPhone', models.CharField(max_length=20)),
                ('insCo', models.CharField(max_length=200)),
                ('dateEffective', models.DateField()),
                ('workersComp', models.CharField(max_length=200)),
                ('wcEffectiveDate', models.DateField()),
                ('pFleet', models.IntegerField()),
                ('forhireFleet', models.IntegerField()),
                ('DOT_Nmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saferdb.Question')),
            ],
        ),
        migrations.AlterField(
            model_name='dot_contacts',
            name='DOT_Num',
            field=models.ForeignKey(default='99999999999', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='saferdb.Question'),
        ),
    ]
