# Generated by Django 2.0.7 on 2018-11-22 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0006_auto_20181121_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caliins_fk',
            name='DOT_Nmb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calIns', to='saferdb.Question'),
        ),
    ]
