# Generated by Django 2.0.7 on 2018-11-22 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0007_auto_20181122_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vin',
            name='DOT_Num',
        ),
        migrations.DeleteModel(
            name='Vin',
        ),
    ]
