# Generated by Django 2.0.7 on 2018-11-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0008_auto_20181122_0249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone', models.CharField(default='', max_length=20)),
                ('DOT_Num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saferdb.Question')),
            ],
        ),
    ]
