# Generated by Django 2.0.7 on 2018-11-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0009_vin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vin',
            old_name='Phone',
            new_name='vin',
        ),
    ]
