# Generated by Django 2.0.7 on 2018-11-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0010_auto_20181122_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caliins_fk',
            old_name='DOT_Nmb',
            new_name='DOTNmb',
        ),
    ]
