# Generated by Django 2.0.7 on 2018-11-23 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0011_auto_20181123_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caliins_fk',
            name='DOTNmb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calins', to='saferdb.Question'),
        ),
    ]
