# Generated by Django 2.0.7 on 2018-12-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0012_auto_20181123_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='caliins_fk',
            name='renewalMonth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
