# Generated by Django 2.0.7 on 2019-01-11 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saferdb', '0013_caliins_fk_renewalmonth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYActiveCorp',
            fields=[
                ('DOSID', models.IntegerField(primary_key=True, serialize=False)),
                ('CurrentEntityName', models.CharField(max_length=200)),
                ('InitialDOSFilingDate', models.CharField(max_length=200)),
                ('County', models.CharField(max_length=200)),
                ('Jurisdiction', models.CharField(max_length=200)),
                ('EntityType', models.CharField(max_length=200)),
                ('DOSProcessName', models.CharField(max_length=200)),
                ('DOSProcessAddress1', models.CharField(max_length=200)),
                ('DOSProcessAddress2', models.CharField(max_length=200)),
                ('DOSProcessCity', models.CharField(max_length=200)),
                ('DOSProcessState', models.CharField(max_length=200)),
                ('DOSProcessZip', models.CharField(max_length=200)),
                ('CEOName', models.CharField(max_length=200)),
                ('CEOAddress1', models.CharField(max_length=200)),
                ('CEOAddress2', models.CharField(max_length=200)),
                ('CEOCity', models.CharField(max_length=200)),
                ('CEOState', models.CharField(max_length=200)),
                ('CEOZip', models.CharField(max_length=200)),
                ('RegisteredAgentName', models.CharField(max_length=200)),
                ('RegisteredAgentAddress1', models.CharField(max_length=200)),
                ('RegisteredAgentAddress2', models.CharField(max_length=200)),
                ('RegisteredAgentCity', models.CharField(max_length=200)),
                ('RegisteredAgentState', models.CharField(max_length=200)),
                ('RegisteredAgentZip', models.CharField(max_length=200)),
                ('LocationName', models.CharField(max_length=200)),
                ('LocationAddress1', models.CharField(max_length=200)),
                ('LocationAddress2', models.CharField(max_length=200)),
                ('LocationCity', models.CharField(max_length=200)),
                ('LocationState', models.CharField(max_length=200)),
                ('LocationZip', models.CharField(max_length=200)),
                ('DOTNmb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saferdb.Question')),
            ],
        ),
    ]
