# Generated by Django 2.0 on 2018-03-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180131_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
