# Generated by Django 2.0.7 on 2018-08-19 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_id',
        ),
    ]
